//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UntSportMeanGreen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class schedule
    {
        public long ScheduleId { get; set; }
        public long CategoryId { get; set; }
        public int TournamentId { get; set; }
        public string Opponent { get; set; }
        public string Location { get; set; }
        public string Result { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
        public string Event { get; set; }
        public string Season { get; set; }
        public string Description { get; set; }
    
        public virtual category category { get; set; }
        public virtual tournament tournament { get; set; }
    }
}
