//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UntSportMeanGreen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tournament
    {
        public tournament()
        {
            this.schedules = new HashSet<schedule>();
        }
    
        public int TournamentId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<schedule> schedules { get; set; }
    }
}
